### ISSUE TITLE
Email authentication

### ISSUE THREAD

**Issue by sedubois** [lipp/login-with#15]
This looks super great, thanks 👍 

I want to migrate my app which has Facebook and email + password auth. Do you plan to add auth using email link and/or login/password?

**Comment by lipp** [comment]
I guess this would add some complexity to this micro service... 
What do you think is required to implement this?

**Comment by sedubois** [comment]
I don't exactly know, which is why I was interested in having it as a service 😅

Anyway, of course I understand if it would be out of scope. Maybe in the future I'd use Graphcool, where it looks like this could be provided out of the box at some point.

Feel free to close 🙂

**Comment by lipp** [comment]
didn't know graphcool. seems cool! thanks
