### ISSUE TITLE
Error! No secret found by uid or name XXX

### ISSUE THREAD

**Issue by sedubois** [lipp/login-with#17]
I ran `now lipp/login-with -e LW_SESSION_SECRET=... -e LW_JWT_SECRET=... -e LW_SUBDOMAIN=... -e LW_FACEBOOK_APPID=... -e FACEBOOK_APPSECRET=...`, but still got the error `Error! No secret found by uid or name "lw-reddit-clientsecret"` (and the error changes every time). It looks like all env vars are required, even the optional ones?

**Comment by lipp** [comment]
I guess it should be `LW_FACEBOOK_APPSECRET` (you are missing the LW_).

Anyhow, this is how my output looks (locally):

```sh
$ LW_SESSION_SECRET=123 LW_JWT_SECRET=123333 LW_SUBDOMAIN=foo.bar.com LW_FACEBOOK_APPID=33 LW_FACEBOOK_APPSECRET=333 node server.js
Using subdomain "https://foo.bar.com" for callback urls
Configured strategies: facebook
Using login with "facebook" strategy
```

**Comment by lipp** [comment]
@sedubois do you still have this issue?

**Comment by sedubois** [comment]
Hi! Thanks for replying. Sorry I haven't been able to come back to this. Feel free to close and I can reopen if I have further issues.

**Comment by lipp** [comment]
Thx
