### ISSUE TITLE
What is it exactly?

### ISSUE THREAD

**Issue by janpio** [lipp/login-with#25]
I wrote this on a Show HN about this, but was (correctly) called out for not opening an issue about that:

> The information on `/login` should probably be on / so I can read somewhere what "Stateless authentication microservice" actually means.
> Also maybe a sentence why this is neat and should be used...

Someone else wrote:

> "Stateless authentication microservice" has only one possible meaning to me. Did you want to ask something more specific, or do you just not know what those (common) words mean?
reply
	
to which I then replied

> The me it means... nothing specific.
> It tells me that is has something to do with login, "without state" (whatever this means in this context) and that it is somehow not a "big service" but very "micro", so probably independent. Stateless and microservice can mean so many things.

So please take this as a bit of feedback: Not everyone really and fully understand the current description.

**Comment by lipp** [comment]
Sorry for not getting the answer you would like to have. It is definitely a legitimate question to ask! I'll add an "About/Why should I use/nedd this" section in the readme or on the homepage/demo.

**Comment by janpio** [comment]
After read some more comments and also understanding the demo at login-with.com I think something along "this takes care of social login and delivers authenticated users with JWT back to your application without storing login information itself" would have helped me.

**Comment by danesparza** [comment]
Can this be deployed as AWS Lambda functions?

**Comment by ProbablePrime** [comment]
@danesparza AWS Lambda is my next target. Due to work in #27 this should be possible with something like https://www.npmjs.com/package/lambda-express or https://github.com/awslabs/aws-serverless-express

Could perhaps work
