### ISSUE TITLE
The demo github login fails

### ISSUE THREAD

**Issue by Chaz6** [lipp/login-with#26]
When I try to log into github on the demo application (https://login-with.now.sh/login) the server responds with:-

```
{"error":{"name":"AuthorizationError","message":"The redirect_uri MUST match the registered callback URL for this application.","code":"redirect_uri_mismatch","uri":"https://developer.github.com/v3/oauth/#redirect-uri-mismatch","status":500}}
```

**Comment by lipp** [comment]
The demo is now on https://login-with.com, because wildcard cookies don't work on .now.sh domains (explicitly disabled by some browsers). Where did you stumble upon that old link? I'd like to remove/fix it.

**Comment by arthow4n** [comment]
Hi there, the link was found in README.md
https://github.com/lipp/login-with#example

**Comment by lipp** [comment]
Thx! I'll remove it.
