### ISSUE TITLE
Reddit strategy doesn't redirect to failure URL on declined auth request

### ISSUE THREAD

**Issue by vitosamson** [lipp/login-with#33]
To reproduce:

1. Go to https://login-with.com/login
2. Login with Reddit
3. Hit the "decline" button on the reddit auth request page

You'll get redirected to https://auth.login-with.com/reddit/callback with `{"error":null,"user":false}`

This is happening because in `routes.js` [here](https://github.com/lipp/login-with/blob/master/src/routes.js#L33), both `error` and `user` are falsy and so it falls through to the `res.json` at the end.

A solution here would probably be to change line 34 to `if (error || !user)` - would you accept a PR for that? I'm not sure if this is happening for other providers, I've only tested with reddit.

**Comment by lipp** [comment]
👍  Sure, PR is very welcomed! I think `if (error || !user)` totally makes sense. Should have  a meaningful error of course...

**Comment by vitosamson** [comment]
https://github.com/lipp/login-with/pull/34

**Comment by vitosamson** [comment]
Hey, any chance we can get a version bump and updated docker image pushed out with this?

**Comment by lipp** [comment]
Sure... tomorrow... promise
