### ISSUE TITLE
Add meta data

### ISSUE THREAD

**Issue by luanmuniz** [lipp/login-with#36]
The API's return more data beyond `username`, `displayName` and `photo`.
It would be nice to have that data together with the requests.

See https://github.com/luanmuniz/login-with/blob/d10d03af244e3cd2049584e66d82072b12c4b357/src/strategies/instagram.js#L25

**Comment by lipp** [comment]
Yeah, would be nice to have more details from the profile. But I'd prefer, not to waste too much cookie size [(limits)[http://browsercookielimits.squawky.net/]).

Maybe we could add an env like `LW_MAX_COOKIE_SIZE` which controls how much meta will be put.

Or the user should specify, additional meta fields should be included (per service), like `LW_GOOGLE_META=foo.bar,baz[0].extra.url` 

Both solutions would require quite some boring work i guess....

**Comment by luanmuniz** [comment]
How about adding a Redis instance to keep the data as optional? If the redis instance exist, keep the extra data in it, otherwise just ignore the extra data.

**Comment by lipp** [comment]
adding redis would make login-with stateful...which would be sad :(
the user would loose the meta data on restart...

how about passing the meta with the redirect body on successful login. than your custom server could handle it?

... but this seems to complicated.... I think `LW_GOOGLE_META` is my favorite. it is explicit and simple. maybe you can come up with a nice env variable syntax?

**Comment by lipp** [comment]
closing in favor of #44
